### ISSUE TITLE
Dashboard battery display not working

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_robot#4]
I get the following backtrace:

```
Node: /rqt_gui_py_node_18721
Time: 1374573994.174
Severity: Error
Published Topics: /diagnostics_toplevel_state, /battery_state, /rosout, /rosout_agg, /motor_status

bad callback: <bound method ScitosDashboard.battery_callback of <scitos_dashboard.scitos_dashboard.ScitosDashboard object at 0x4060cb0>>
Traceback (most recent call last):
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rospy/topics.py", line 683, in _invoke_callback
    cb(msg)
  File "/opt/strands/strands_catkin_ws/src/scitos_robot/scitos_dashboard/src/scitos_dashboard/scitos_dashboard.py", line 59, in battery_callback
    self._batteries.set_power_state(msg)
  File "/opt/strands/strands_catkin_ws/src/scitos_robot/scitos_dashboard/src/scitos_dashboard/scitos_battery.py", line 46, in set_power_state
    self.update_perc(msg.relative_capacity)
AttributeError: 'BatteryState' object has no attribute 'relative_capacity'


Location:
topics.py:_invoke_callback:686

----------------------------------------------------------------------------------------------------

```

**Comment by cburbridge** [comment]
I know the problem, will fix it when next on the robot.
